version: '3'

services:
  web:
    image: nodejs-angular-starter
    build:
      context: .
      args:
        - NODE_ENV
    environment:
      - NODE_ENV
      # If we are running through docker-compose, allows access to the database
      - WEB_CONF_DB_URI
      - WEB_CONF_LOGS_DIR
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - '~/dockers_data/web/logs:/logs'
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - 'mongodata:/data/db'

  # Test database used for running tests only
  test-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27019:27017

volumes:
  mongodata: